//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Deneyimlerim
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Bu Alan Boþ Geçilemez")]
        public string Baslik { get; set; }
        [Required(ErrorMessage = "Bu Alan Boþ Geçilemez")]
        public string AltBaslik { get; set; }
        public string Aciklama { get; set; }
        public string Tarih { get; set; }
    }
}
